-------------- Customer Insights ----------------
-- How many unique customers are in the dataset?
select * from TargetDB..customers

select COUNT( distinct customer_unique_id) as unique_customers
from TargetDB..customers

-- What is the total number of orders placed by each customer?
select * from TargetDB..order_items

select
c.customer_unique_id, count(o.order_id) as total_order
from TargetDB..customers c
join TargetDB..orders o on c.customer_id = o.customer_id
group by c.customer_unique_id
order by total_order desc

-- What is the average order value per customer?

select
c.customer_id, c.customer_unique_id, avg(oi.price) as avg_order_val
from TargetDB..customers c
join TargetDB..orders o on c.customer_id = o.customer_id
join TargetDB..order_items oi on o.order_id = oi.order_id
group by c.customer_id, c.customer_unique_id
order by avg_order_val desc

-- What is the geographical distribution of customers?
select * from TargetDB..geolocation

select
g.geolocation_state, count(distinct c.customer_unique_id) as count_customers
from TargetDB..geolocation g
join TargetDB..customers c on g.geolocation_zip_code_prefix = c.customer_zip_code_prefix
group by geolocation_state
order by g.geolocation_state


------------ Order Analysis --------------
-- What is the total number of orders placed?
select * from TargetDB..orders

select COUNT(order_id) as tt_orders
from TargetDB..orders

-- What is the monthly distribution of orders?

select DATEPART(MONTH, order_purchase_timestamp) as monthh, COUNT(order_id) as tt_orders
from TargetDB..orders
group by DATEPART(MONTH, order_purchase_timestamp)
order by DATEPART(MONTH, order_purchase_timestamp)

-- What is the average order value?
select * from TargetDB..order_items

select avg(tt_amount) as avg_order_value
from (
select order_id, sum(price + freight_value) as tt_amount
from TargetDB..order_items
group by order_id
) as order_tts


-- What is the distribution of order statuses (e.g., delivered, canceled, etc.)?

select
order_status, count(order_id) as orders
from TargetDB..orders
group by order_status


--------------- Product Insights ----------------
-- What are the top 10 best-selling products?
select * from TargetDB..products,TargetDB..order_items

select top 10
p.product_id, p.product_category, count(oi.order_item_id) as orders
from TargetDB..products p
join TargetDB..order_items oi on p.product_id = oi.product_id
group by p.product_id, p.product_category
order by orders desc

-- What is the total revenue generated by each product?

select 
p.product_id, p.product_category, round(sum(oi.price), 2) as revenue
from TargetDB..products p
join TargetDB..order_items oi on p.product_id = oi.product_id
group by p.product_id, p.product_category
order by revenue desc

-- What is the average price of products sold?

select avg(price) as avg_price
from TargetDB..order_items

-- What are the most frequently bought products together?

SELECT oi1.product_id AS product1, oi2.product_id AS product2, COUNT(*) AS times_bought_together
FROM TargetDB..order_items oi1
JOIN TargetDB..order_items oi2 ON oi1.order_id = oi2.order_id AND oi1.product_id < oi2.product_id
GROUP BY oi1.product_id, oi2.product_id
ORDER BY times_bought_together DESC

------------------ Sales Performance --------------------
-- Which sellers have the highest sales?
select * from TargetDB..sellers
select * from TargetDB..order_items

select top 10
s.seller_id, s.seller_city, sum(oi.price) as sales
from TargetDB..sellers s
join TargetDB..order_items oi on s.seller_id = oi.seller_id
group by s.seller_id, s.seller_city
order by sales desc

-- How does the sales performance vary by geographical location?

select 
s.seller_state, round(sum(oi.price), 2) as sales
from TargetDB..sellers s
join TargetDB..order_items oi on s.seller_id = oi.seller_id
group by s.seller_state
order by sales desc

-- What are the peak sales periods?

select DATEPART(month, order_purchase_timestamp) as mth, round(sum(oi.price), 2) as peak_sales
from TargetDB..orders o
join TargetDB..order_items oi on o.order_id = oi.order_id
group by DATEPART(month, order_purchase_timestamp)
order by peak_sales desc

--------------- Payment Analysis ---------------
-- What are the different payment methods used, and how frequently is each used?
select * from TargetDB..payments 

select
payment_type, count(*) as count_pay
from TargetDB..payments 
group by payment_type

-- What is the total amount of payments processed for each payment method?

select
payment_type, round(SUM(payment_value), 2) as tt_amount
from TargetDB..payments
group by payment_type
order by tt_amount desc

-- What is the distribution of payment amounts (e.g., small, medium, large payments)?

SELECT CASE
    WHEN payment_value < 50 THEN 'Small'
    WHEN payment_value BETWEEN 50 AND 200 THEN 'Medium'
    ELSE 'Large'
    END AS payment_range, COUNT(*) AS count_amount
FROM TargetDB..payments
group by CASE
    WHEN payment_value < 50 THEN 'Small'
    WHEN payment_value BETWEEN 50 AND 200 THEN 'Medium'
    ELSE 'Large'
    END

-- What is the average payment value?

select 
round(avg(payment_value), 2) as avg_pay_value
from TargetDB..payments

-------------------- Delivery Performance -------------------
-- What is the average delivery time for orders?
select * from TargetDB..orders

SELECT AVG(DATEDIFF(DAY, order_purchase_timestamp, order_delivered_customer_date)) AS avg_delivery_time_days
FROM TargetDB..orders
WHERE order_status = 'delivered'

-- Which geographical areas have the longest delivery times?

SELECT c.customer_state, AVG(DATEDIFF(DAY, o.order_purchase_timestamp, o.order_delivered_customer_date)) AS avg_delivery_time_days
FROM TargetDB..orders o
join TargetDB..customers c on o.customer_id = c.customer_id
WHERE order_status = 'delivered'
group by c.customer_state
order by avg_delivery_time_days desc

-- What percentage of orders are delivered late?

SELECT ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM TargetDB..orders WHERE order_status = 'delivered'), 2) AS late_delivery_percentage
FROM TargetDB..orders
WHERE order_delivered_customer_date > order_estimated_delivery_date

-- What is the relationship between order value and delivery time?

select
AVG(oi.price) as avg_order_value, AVG(DATEDIFF(DAY, o.order_purchase_timestamp, o.order_delivered_customer_date)) AS avg_delivery_time_days
from TargetDB..orders o
join TargetDB..order_items oi on o.order_id = oi.order_id
WHERE o.order_status = 'delivered'

----------------- Customer Segmentation ----------------------
-- What are the characteristics of the top 10% of customers by total spending?

select top 10
c.customer_id, c.customer_unique_id, round(SUM(oi.price), 2) AS total_spent
from TargetDB..customers c
join TargetDB..orders o on c.customer_id = o.customer_id
join TargetDB..order_items oi on o.order_id = oi.order_id
group by c.customer_id, c.customer_unique_id
order by total_spent desc

-- How do order frequencies differ between new and returning customers?

with cte as 
(
select o.customer_id, count(o.order_id) as count_order
from TargetDB..orders o
join TargetDB..order_items oi on o.order_id = oi.order_id
group by o.customer_id
)
select 
	case
		when count_order = 1 then 'New'
		Else 'Returning' END as customer_type,
	count(*) as customers_order
from cte
group by case
		when count_order = 1 then 'New'
		Else 'Returning' END

-- What is the average order value for new vs. returning customers?

with cte as 
(
select o.customer_id, count(o.order_id) as count_order
from TargetDB..orders o
join TargetDB..order_items oi on o.order_id = oi.order_id
group by o.customer_id
)
select 
	case
		when count_order = 1 then 'New'
		Else 'Returning' END as customer_type,
	avg(oi.price) as customers_order
from cte t
JOIN TargetDB..orders o ON t.customer_id = o.customer_id
JOIN TargetDB..order_items oi ON o.order_id = oi.order_id
group by case
		when count_order = 1 then 'New'
		Else 'Returning' END

-- Which geographical areas have the highest customer spending?

select 
c.customer_state, round(SUM(oi.price), 2) as spending
from TargetDB..customers c
join TargetDB..orders o on c.customer_id = o.customer_id
join TargetDB..order_items oi on o.order_id = oi.order_id
group by c.customer_state
order by spending desc


------------------- Return and Refund Analysis --------------------
-- What percentage of orders are Canceled?

SELECT ROUND(100.0 * COUNT(*) / (SELECT COUNT(*) FROM TargetDB..orders), 2) AS canceled_percentage
FROM TargetDB..orders
WHERE order_status = 'Canceled' 

-- What is the average value of Canceled orders?

select
o.order_status, avg(oi.price) as avg_value
from TargetDB..orders o
join TargetDB..order_items oi on o.order_id = oi.order_id
group by o.order_status
having o.order_status = 'Canceled'

-- Which products have the highest return rates?

select 
p.product_id, p.product_category, count(o.order_id) as return_rate
from TargetDB..products p
join TargetDB..order_items oi on p.product_id = oi.product_id
join TargetDB..orders o on oi.order_id = o.order_id
where o.order_status = 'Canceled'
group by p.product_id, p.product_category
order by return_rate desc
